In [1]:
# autoreload
%load_ext autoreload
%autoreload 2


In [28]:
from torch_geometric.data import DataLoader
from mldec.models import initialize
import copy

import torch
from torch_geometric.loader import DataLoader
import copy
import time

from mldec.utils import evaluation, training

In [29]:
dummy_model_config = {
        "model": "gnn",
        "gcn_depth": 2,# !OVERWRITE
        "gcn_min": 16,# !OVERWRITE
        "mlp_depth": 3,# !OVERWRITE
        "mlp_max": 8,# !OVERWRITE  
		"patience": 100,  
		"opt": "adam",
		"input_dim": 0,
		"output_dim": 1,
		"lr": 0.003, # !OVERWRITE
		"dropout": 0.05, # 
}
reps_config = copy.deepcopy(dummy_model_config)
reps_config.update({"input_dim": 2})
toric_config = copy.deepcopy(dummy_model_config)
toric_config.update({"input_dim": 5})

reps_criterion = torch.nn.BCEWithLogitsLoss()
reps_model_wrapper = initialize.initialize_model(reps_config)
reps_optimizer, scheduler = training.initialize_optimizer(reps_config, reps_model_wrapper.model.parameters())

toric_criterion = torch.nn.BCEWithLogitsLoss()
toric_model_wrapper = initialize.initialize_model(toric_config)
toric_optimizer, scheduler = training.initialize_optimizer(toric_config, toric_model_wrapper.model.parameters())


In [48]:
from mldec.datasets import reps_exp_rep_code_data, reps_toric_code_data
n_data = 2048
repcode_dataset_config = {
    "code_size": 5,
    "repetitions": 5,
    "beta": 1
}
reps_data_tr, triv_tr, _  = reps_exp_rep_code_data.sample_dataset(n_data, repcode_dataset_config, None, seed=None)

# toric_dataset_config = {
#     "repetitions": 4,
#     "code_size": 7,
#     "p": 0.05,
#     "beta": 1,
# }
# toric_data_tr, triv_tr, _, _ = reps_toric_code_data.sample_dataset(n_data, toric_dataset_config, None, seed=None)
# batch_size = 128

# toric_training_dataloader = DataLoader(toric_data_tr, batch_size=batch_size, shuffle=True)
# reps_training_dataloader = DataLoader(reps_data_tr, batch_size=batch_size, shuffle=True)





total data length:  2048
(2048, 5, 4)
(2048, 20)
[ True  True  True ...  True  True  True]
[[0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
[[0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

In [ ]:

max_epochs = 100
# for epoch in range(max_epochs):
#     for batch in reps_training_dataloader:
#         try:
#             reps_model_wrapper.training_step(batch, reps_optimizer, reps_criterion)
#         except ValueError:
#             print(epoch)
#             print(batch.x.shape, batch.y.shape)
for epoch in range(max_epochs):
    for batch in toric_training_dataloader:
        # print(batch.x.shape, batch.y.shape)
        toric_model_wrapper.training_step(batch, toric_optimizer, toric_criterion)



In [19]:
batch.x.shape

torch.Size([4438, 5])

In [10]:
reps_training_dataloader.batch

AttributeError: 'DataLoader' object has no attribute 'batch'

In [68]:
v = np.arange(30)
v[:33]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
from mldec.datasets.reps_toric_code_data import *



In [6]:
seed = None
n_data = 10
repetitions = dataset_config.get("repetitions") # "cycles" of measurement
code_size = dataset_config.get("code_size")
sampler, detector_coordinates, _ = make_sampler(dataset_config, seed=seed)

# get the surface code grid:
mask = syndrome_mask(code_size, repetitions)
# sample detection events and observable flips
stim_data, observable_flips = sampler.sample(shots=int(n_data), separate_observables=True)
non_empty_indices = (np.sum(stim_data, axis = 1) != 0)
trivial_count = len(observable_flips[~ non_empty_indices])
stim_data = stim_data[non_empty_indices, :]
observable_flips = observable_flips[non_empty_indices]

In [8]:
stim_data.shape

(10, 192)

In [141]:
# Function for creating a single graph as a PyG Data object


In [50]:
from mldec.datasets.reps_toric_code_data import sample_dataset
dataset_config = {
    "repetitions": 4,
    "code_size": 7,
    "p": 0.05,
    "beta": 1,
}
data, trivial_count, _, _ = sample_dataset(n_data = 30, dataset_config = dataset_config, device = None, seed = None)


In [67]:
for obj in data:
    print(obj.x, obj.y)

tensor([[1., 0., 0., 1., 1.],
        [1., 0., 0., 1., 2.],
        [1., 0., 0., 3., 2.],
        [1., 0., 0., 3., 3.],
        [1., 0., 0., 5., 2.],
        [1., 0., 0., 5., 3.],
        [0., 1., 1., 1., 3.],
        [1., 0., 1., 2., 1.],
        [1., 0., 1., 2., 2.],
        [0., 1., 1., 3., 2.],
        [0., 1., 1., 3., 3.],
        [1., 0., 1., 4., 1.],
        [1., 0., 1., 4., 2.],
        [0., 1., 1., 5., 2.],
        [0., 1., 1., 5., 3.],
        [1., 0., 1., 6., 1.],
        [1., 0., 1., 6., 4.],
        [0., 1., 1., 7., 1.],
        [0., 1., 1., 7., 2.],
        [0., 1., 2., 0., 1.],
        [0., 1., 2., 0., 4.],
        [1., 0., 2., 1., 1.],
        [1., 0., 2., 1., 2.],
        [0., 1., 2., 2., 0.],
        [0., 1., 2., 2., 2.],
        [0., 1., 2., 2., 3.],
        [1., 0., 2., 3., 1.],
        [1., 0., 2., 3., 2.],
        [1., 0., 2., 3., 3.],
        [1., 0., 2., 3., 4.],
        [0., 1., 2., 4., 0.],
        [0., 1., 2., 4., 1.],
        [0., 1., 2., 6., 2.],
        [0

In [43]:
from mldec.utils.graph_representation import *

i = 3


syndrome_3D = stim_to_syndrome_3D(mask, detector_coordinates, stim_data[i])
syndrome_2D = syndrome_3D[0,:,:] # mockup repetition code data for n=5 (syndromes are length 4)
# get defect indices: 
defects, defect_indices_triple = get_node_list_3D(syndrome_3D)
# defects_2D, defect_indices_double = get_node_list_2D(syndrome_2D)



# Use helper function to create node feature matrix as torch.tensor
# (X, Z, N-dist, W-dist, time-dist)
X = get_node_feature_matrix(defects, defect_indices_triple, num_node_features = 5)

# # currently, X_2D is redundant. Single stabilier means that the first axis will always contain '1'...
# # X_2D can just be replaced with np.nonzero(syndrome_2D) which are x_coords, t_coords for all faults.
# # should be 2-D: [d_left, d_time]
# X_2D = get_node_feature_matrix_rep_code(defects_2D, defect_indices_double)


# get the logical equivalence class:
true_eq_class = np.array([int(observable_flips[i])])
# map to graph representation

# first element is 'X', the 5-D [is_x, is_z, d_north, d_west, d_time]
graph_3D = graph_representation.get_3D_graph(syndrome_3D = syndrome_3D,
                    target = true_eq_class,
                    power = 2,
                    m_nearest_nodes = None)

# graph_2D = get_2D_graph(syndrome_2D = syndrome_2D, target=true_eq_class, power=2, m_nearest_nodes=None)




C:\Users\peter\AppData\Local\Temp\ipykernel_3904\4144587285.py:25: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  true_eq_class = np.array([int(observable_flips[i])])


In [14]:
for i in range(5):
    print(graph[i])

[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 3.]
 [0. 1. 2. 2. 3.]]
[[0 0 0 1 1 1 2 2 2 3 3 3]
 [1 2 3 0 2 3 0 1 3 0 1 2]]
[[1.        ]
 [0.11111111]
 [0.11111111]
 [1.        ]
 [0.25      ]
 [0.25      ]
 [0.11111111]
 [0.25      ]
 [1.        ]
 [0.11111111]
 [0.25      ]
 [1.        ]]
[[1.]]


IndexError: list index out of range